name: Production Deployment

on:
  push:
    branches: [ main ]
  # Remove pull_request - now handled by pr-fast.yml

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Wait for Netlify preview deployment
      uses: jakepartusch/wait-for-netlify-action@v1.4
      id: wait-for-netlify
      with:
        site_name: 'deft-florentine-69dcb4'
        max_timeout: 600
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
    
    - name: Run Playwright tests against preview
      run: npm test
      env:
        BASE_URL: ${{ steps.wait-for-netlify.outputs.url }}
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Run unit tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Trigger Netlify deployment after tests pass
      if: success()
      run: |
        echo "✅ All tests passed! Safe to deploy to production."
        echo "Netlify will auto-deploy this commit since it was pushed to main."
        echo "If this fails, deployment should be blocked manually in Netlify."