name: Fast PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build check
      run: npm run build:dev
    
    - name: Install Playwright (Chromium only)
      run: npx playwright install --with-deps chromium
    
    - name: Fast smoke tests
      run: |
        # Start dev server and wait for it to be ready
        npm run dev &
        DEV_PID=$!
        
        # Wait for dev server to be available
        echo "Waiting for dev server to start..."
        for i in {1..30}; do
          if curl -f http://localhost:5173 >/dev/null 2>&1; then
            echo "Dev server is ready!"
            break
          fi
          sleep 2
        done
        
        # Run key tests that would catch deployment-breaking issues
        npx playwright test tests/smoke.spec.ts tests/homepage.spec.ts tests/navigation.spec.ts --project=chromium
        
        # Clean up
        kill $DEV_PID 2>/dev/null || true
      env:
        BASE_URL: http://localhost:5173