name: Fast PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Build check
      run: npm run build:dev
    
    - name: Install Playwright (Chromium only)
      run: npx playwright install --with-deps chromium
    
    - name: Fast smoke tests
      run: |
        # Run key tests on localhost with Chromium only
        npm run dev & 
        sleep 10
        npx playwright test tests/smoke.spec.ts tests/homepage.spec.ts --project=chromium
        pkill -f "npm run dev" || true
      env:
        BASE_URL: http://localhost:5173